// <auto-generated />
using System;
using HCSpillage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCSpillage.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221212130437_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HCSpillage.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d8279a54-566d-4c42-8f45-c62e8879dd4a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0c55d53d-e277-4fd2-8f31-11c4d71c75fb",
                            Email = "Admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFsiaMLs0RDpJZS38/YcGBaqM7wPFRiN7FqzXHDXQ1AEdLS1RGavhOa/cc8UQlfqpw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "129dc071-b304-4b3e-981c-579cfbb9cac8",
                            TwoFactorEnabled = false,
                            UserName = "Admin@gmail.com"
                        },
                        new
                        {
                            Id = "5a805103-d331-4154-93e8-d6ca4aec72ba",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "beee4111-7b26-432a-afe6-bb20f6bae4fd",
                            DeviceId = "A123",
                            Email = "Emma@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "EMMA@GMAIL.COM",
                            NormalizedUserName = "EMMA@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENFcZLdahy5IdI+YBHz1FPSzh3pbhB5+Y042U0a31SucV2BimQbEozT/it5QODIhjA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "99221429-67cb-4b9f-a6da-aff804a9e736",
                            TwoFactorEnabled = false,
                            UserName = "Emma@gmail.com"
                        },
                        new
                        {
                            Id = "36a578b8-e098-475b-8425-36290f6b30c8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7318e98c-9682-4aaf-b7d7-2b8aac9af443",
                            DeviceId = "A423",
                            Email = "abc@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ABC@GMAIL.COM",
                            NormalizedUserName = "ABC@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOeELIk4HVL51TH5dVBkQi4BcIi1k0Fc5Kch/ts49kXP/BMIsyzLiUeR3Hpo91vagg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d6793e89-9b69-488b-af64-a0f8f1cbe1a3",
                            TwoFactorEnabled = false,
                            UserName = "abc@GMAIL.COM"
                        });
                });

            modelBuilder.Entity("HCSpillage.Models.DataPresentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Config")
                        .HasColumnType("bit");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Verify")
                        .HasColumnType("bit");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Config = true,
                            Data = "No Gas Detected",
                            DeviceId = "A123",
                            Email = "emma@gmail.com",
                            Location = "Uyo",
                            Status = "On",
                            Time = "13:04",
                            Verify = false,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 2,
                            Config = true,
                            Data = "Gas detected",
                            DeviceId = "A123",
                            Email = "emma.@gmail.com",
                            Location = "Uyo",
                            Status = "On",
                            Time = "13:04",
                            Verify = true,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 3,
                            Config = false,
                            Data = "Gas detected",
                            DeviceId = "A123",
                            Email = "emma.@gmail.com",
                            Location = "Uyo",
                            Status = "On",
                            Time = "13:04",
                            Verify = true,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 4,
                            Config = false,
                            Data = "Gas detected",
                            DeviceId = "A423",
                            Email = "abc@gmail.com",
                            Location = "Oron",
                            Status = "On",
                            Time = "13:04",
                            Verify = false,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 5,
                            Config = false,
                            Data = "Gas detected",
                            DeviceId = "A423",
                            Email = "abc@gmail.com",
                            Location = "Oron",
                            Status = "On",
                            Time = "13:04",
                            Verify = false,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 6,
                            Config = false,
                            Data = "No Gas Detected",
                            DeviceId = "A423",
                            Email = "abc@gmail.com",
                            Location = "Oron",
                            Status = "On",
                            Time = "13:04",
                            Verify = true,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 7,
                            Config = true,
                            Data = "No Gas Detected",
                            DeviceId = "A423",
                            Email = "abc@gmail.com",
                            Location = "Oron",
                            Status = "On",
                            Time = "13:04",
                            Verify = true,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 8,
                            Config = false,
                            Data = "Gas detected",
                            DeviceId = "A423",
                            Email = "abc@gmail.com",
                            Location = "Oron",
                            Status = "On",
                            Time = "13:04",
                            Verify = false,
                            date = "12/12/2022"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "783c11bc-75a6-463a-b8aa-7a2697f6ef4f",
                            ConcurrencyStamp = "867617e1-e5c2-44ba-82d3-d2eda13738ba",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "a4719535-4dbb-4ea6-a41f-672c1a7f243e",
                            ConcurrencyStamp = "cd78d67e-4c23-4338-b537-1887f29af27d",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "d8279a54-566d-4c42-8f45-c62e8879dd4a",
                            RoleId = "783c11bc-75a6-463a-b8aa-7a2697f6ef4f"
                        },
                        new
                        {
                            UserId = "5a805103-d331-4154-93e8-d6ca4aec72ba",
                            RoleId = "a4719535-4dbb-4ea6-a41f-672c1a7f243e"
                        },
                        new
                        {
                            UserId = "36a578b8-e098-475b-8425-36290f6b30c8",
                            RoleId = "a4719535-4dbb-4ea6-a41f-672c1a7f243e"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HCSpillage.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HCSpillage.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCSpillage.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HCSpillage.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
