// <auto-generated />
using System;
using HCSpillage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCSpillage.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221212151637_modifiedAdminInterface")]
    partial class modifiedAdminInterface
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HCSpillage.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d8279a54-566d-4c42-8f45-c62e8879dd4a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8d9c912b-d114-4f77-a449-3b5c3affa471",
                            Email = "Admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDW9DBU/oFjcpH1uXHqzA41un4qQCgQJWSP6Ix4aLj4SlOzOKvNeQyP2Q7c7CLeHLw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0bb49f60-8c29-42ed-9a0d-bdeb4e57398b",
                            TwoFactorEnabled = false,
                            UserName = "Admin@gmail.com"
                        },
                        new
                        {
                            Id = "5a805103-d331-4154-93e8-d6ca4aec72ba",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "de11e71c-756a-4331-96ae-c58256a44628",
                            DeviceId = "A123",
                            Email = "Emma@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "EMMA@GMAIL.COM",
                            NormalizedUserName = "EMMA@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBf8ZMWQwaA/FLgIb/xHPrrs3jjy7P5DrFvvEUFWVj3nKb35ehM5YSQnu8RcpJDvjg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b96a51fd-d957-4857-ac09-754e199cc261",
                            TwoFactorEnabled = false,
                            UserName = "Emma@gmail.com"
                        },
                        new
                        {
                            Id = "36a578b8-e098-475b-8425-36290f6b30c8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eada4d20-4220-4266-82ca-ace0070df95c",
                            DeviceId = "A423",
                            Email = "abc@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ABC@GMAIL.COM",
                            NormalizedUserName = "ABC@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMmEBQ1WQNePG2QVxkgEWlVmz+nu/XnZoOxIOktXLU9fNmu3fuf7G7ZIWv95y6J5yQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b7249054-e006-45ab-abbd-69b9b37b8180",
                            TwoFactorEnabled = false,
                            UserName = "abc@GMAIL.COM"
                        });
                });

            modelBuilder.Entity("HCSpillage.Models.DataPresentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Config")
                        .HasColumnType("bit");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Verify")
                        .HasColumnType("bit");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Config = true,
                            Data = "Yes",
                            DeviceId = "A123",
                            Email = "emma@gmail.com",
                            Location = "Uyo",
                            Status = "On",
                            Time = "15:16",
                            Verify = false,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 2,
                            Config = true,
                            Data = "Yes",
                            DeviceId = "A123",
                            Email = "emma.@gmail.com",
                            Location = "Uyo",
                            Status = "On",
                            Time = "15:16",
                            Verify = true,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 3,
                            Config = false,
                            Data = "Yes",
                            DeviceId = "A123",
                            Email = "emma@gmail.com",
                            Location = "Uyo",
                            Status = "On",
                            Time = "15:16",
                            Verify = true,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 4,
                            Config = false,
                            Data = "Yes",
                            DeviceId = "A423",
                            Email = "abc@gmail.com",
                            Location = "Oron",
                            Status = "On",
                            Time = "15:16",
                            Verify = false,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 5,
                            Config = false,
                            Data = "Yes",
                            DeviceId = "A423",
                            Email = "abc@gmail.com",
                            Location = "Oron",
                            Status = "On",
                            Time = "15:16",
                            Verify = false,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 6,
                            Config = false,
                            Data = "No",
                            DeviceId = "A423",
                            Email = "abc@gmail.com",
                            Location = "Oron",
                            Status = "On",
                            Time = "15:16",
                            Verify = true,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 7,
                            Config = true,
                            Data = "No",
                            DeviceId = "A423",
                            Email = "abc@gmail.com",
                            Location = "Oron",
                            Status = "On",
                            Time = "15:16",
                            Verify = true,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 8,
                            Config = false,
                            Data = "No",
                            DeviceId = "A423",
                            Email = "abc@gmail.com",
                            Location = "Oron",
                            Status = "On",
                            Time = "15:16",
                            Verify = false,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 9,
                            Config = false,
                            Data = "No",
                            DeviceId = "B123",
                            Email = "luis@gmail.com",
                            Location = "Oron",
                            Status = "On",
                            Time = "15:16",
                            Verify = false,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 10,
                            Config = false,
                            Data = "No",
                            DeviceId = "A982",
                            Email = "Samuel@gmail.com",
                            Location = "Oron",
                            Status = "On",
                            Time = "15:16",
                            Verify = false,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 11,
                            Config = false,
                            Data = "No",
                            DeviceId = "A093",
                            Email = "Oboho@gmail.com",
                            Location = "Oron",
                            Status = "On",
                            Time = "15:16",
                            Verify = false,
                            date = "12/12/2022"
                        },
                        new
                        {
                            Id = 12,
                            Config = false,
                            Data = "No",
                            DeviceId = "A938",
                            Email = "Solomon@gmail.com",
                            Location = "Oron",
                            Status = "OFF",
                            Time = "15:16",
                            Verify = true,
                            date = "12/12/2022"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "783c11bc-75a6-463a-b8aa-7a2697f6ef4f",
                            ConcurrencyStamp = "bf8026e9-bb3e-4d41-ba27-d382b19dabc8",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "a4719535-4dbb-4ea6-a41f-672c1a7f243e",
                            ConcurrencyStamp = "091307ab-881e-4abf-a3d4-22d8dd73b478",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "d8279a54-566d-4c42-8f45-c62e8879dd4a",
                            RoleId = "783c11bc-75a6-463a-b8aa-7a2697f6ef4f"
                        },
                        new
                        {
                            UserId = "5a805103-d331-4154-93e8-d6ca4aec72ba",
                            RoleId = "a4719535-4dbb-4ea6-a41f-672c1a7f243e"
                        },
                        new
                        {
                            UserId = "36a578b8-e098-475b-8425-36290f6b30c8",
                            RoleId = "a4719535-4dbb-4ea6-a41f-672c1a7f243e"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HCSpillage.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HCSpillage.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCSpillage.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HCSpillage.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
